/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javamessenger;

/**
 *
 * @author laril
 */
public class MainWindow extends javax.swing.JFrame {
    
    private String nickname;
    
    //Instancia para o popup de cadastro
    PopUpCadastro viewPopUpCadastro;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        viewPopUpCadastro = new PopUpCadastro();
        nickname = "";
    }
    
    //Imprime no label de nickname o nickname salvo na classe
    private void mostrarNickname(){
        lblNickname.setText(nickname);
    }
    
    //Imprime no panel uma string com as mensagens
    private void mostrarMensagens(String mensagens){
        txtChat.setText(mensagens);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupCadastro = new javax.swing.JFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMensagem = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        lblNickname = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        boxBroadcast = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout popupCadastroLayout = new javax.swing.GroupLayout(popupCadastro.getContentPane());
        popupCadastro.getContentPane().setLayout(popupCadastroLayout);
        popupCadastroLayout.setHorizontalGroup(
            popupCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        popupCadastroLayout.setVerticalGroup(
            popupCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat - Sistemas Distribuídos");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtMensagem.setBackground(new java.awt.Color(255, 255, 255));
        txtMensagem.setColumns(20);
        txtMensagem.setLineWrap(true);
        txtMensagem.setRows(1);
        txtMensagem.setWrapStyleWord(true);
        txtMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMensagemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(txtMensagem);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnConfig.setText("Cadastrar");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        lblNickname.setBackground(new java.awt.Color(255, 255, 255));
        lblNickname.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNickname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNickname.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnConfig)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnConfig)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        txtChat.setEditable(false);
        txtChat.setBackground(new java.awt.Color(169, 195, 225));
        txtChat.setColumns(20);
        txtChat.setLineWrap(true);
        txtChat.setRows(5);
        txtChat.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtChat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 347, 275));

        boxBroadcast.setBackground(new java.awt.Color(204, 255, 204));
        boxBroadcast.setText("Broadcast");
        boxBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBroadcastActionPerformed(evt);
            }
        });
        getContentPane().add(boxBroadcast, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 6, 160, -1));

        listaUsuarios.setBackground(new java.awt.Color(204, 255, 204));
        listaUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaUsuarios.setSelectionBackground(new java.awt.Color(204, 153, 255));
        jScrollPane1.setViewportView(listaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 30, 166, 251));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBroadcastActionPerformed

    }//GEN-LAST:event_boxBroadcastActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        viewPopUpCadastro.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnConfigActionPerformed

    //Trata das acoes que devem ser realizadas no evento do botao de enviar mensagem
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //Usar o nickname e o txtMensagem.getText para obter a mensagem a ser enviada ao socket;
        //Fornecer a lista de mensagens para ser impressa no chat (uma String);
        //Imprimir a lista de mensagens com:
        //mostrarMensagens(texto das mensagens);
        if(!viewPopUpCadastro.nickname.isEmpty() && !viewPopUpCadastro.caminho.isEmpty() && !viewPopUpCadastro.porta.isEmpty()){
            if(boxBroadcast.isSelected()){
                //Enviar para todos os users que estarão registrados
                //Está mostrando quando fica broadcast ou não
                mostrarMensagens("Broadcast\n");
            }
            else{
                //Exemplo só para testes
                String textoEnviado = txtMensagem.getText();
                String indices = "";
                indices += this.nickname + " para ";
                int[] selecionados = listaUsuarios.getSelectedIndices();
                //Pegar todos os selecionados na lista para enviar para eles
                for(int i = 0; i < selecionados.length; i++){
                    indices += "user " + selecionados[i] + " ";
                }
                indices += ": " + textoEnviado + "\n";
                mostrarMensagens(indices);

            }
        }

    }//GEN-LAST:event_btnEnviarActionPerformed

    //Imprime o nickname no label se houver click do mouse no panel
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        nickname = viewPopUpCadastro.nickname;
        mostrarNickname();
    }//GEN-LAST:event_jPanel2MouseClicked

    //Imprime o nickname no label se houver click do mouse na text area de envio de mensagens
    private void txtMensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMensagemMouseClicked
        nickname = viewPopUpCadastro.nickname;
        mostrarNickname();
    }//GEN-LAST:event_txtMensagemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxBroadcast;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JList<String> listaUsuarios;
    private javax.swing.JFrame popupCadastro;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextArea txtMensagem;
    // End of variables declaration//GEN-END:variables
}
